### ISSUE TITLE
pigdice game test

### ISSUE THREAD

**Issue by juhan00** [05house/pigdice#1]
##Tasks

- [x] Create random function
- [x] Add game logic
- [x] Add game player function
