### ISSUE TITLE
juhan pigdice

### ISSUE THREAD

**Issue by juhan00** [05house/pigdice#10]
#Tasks

- [x] html 화면 추가하기 
- [x]  js 파일 버튼과 연동되게 변경하기 
- [x]  홀드 및 새로 시작하기 기능 추가
- [x]  코드 정리하기

**Comment by juhan00** [comment]
#Tasks

- [x] git flow 사용법 테스트
- [x] 플레이어 승리 메시지 순서 변경, 초기화 오류 수정
