### ISSUE TITLE
danbi pigdice

### ISSUE THREAD

**Issue by danbi506** [05house/pigdice#12]
## Tasks

- [x] html로 틀짜기
- [x] 주사위 6개의 값 랜덤 프린트
- [x] 랜덤으로 나온 값들 더하기 프린트
- [x] 1이 아니면 더하기 프린트
- [x] 1이 나오면 리셋,  다음 기회에 프린트
