### ISSUE TITLE
soohyun pigdice 

### ISSUE THREAD

**Issue by soohyun21** [05house/pigdice#6]
##Tasks

- [x] html 파일 생성하고 버튼 만들기
- [x] 1이 나오면 "0점입니다" 출력 
- [x] 총점이 100 넘으면 "100점 달성!!!" 출력
- [x] 마지막 else로 득점과 총점 출력
